<pre>
<?php
    require_once('include/DBManager.php');
    $db_manager=DBManager::getInstance();
    $db_manager->install();//optional
    $db_manager->connect();
    /*
    $db_manager->insertStudent(array(
            DBContract::$Students_Col_Name=>'omar',
        DBContract::$Students_Col_Email=>'omar@kazoum.com',
        DBContract::$Students_Col_DateAdmission=>date('Y-m-d'),
        DBContract::$Students_Col_EnrollNbr=>uniqid(),
        DBContract::$Students_Col_Phone=>'0610204662'
        ));
    */
    //print_r($db_manager->getAllStudents());
    /*$s=array(
        DBContract::$Students_Col_Name=>'khalil',
        DBContract::$Students_Col_Email=>'email@gmail.com',
        DBContract::$Students_Col_Phone=>'9988887',
        DBContract::$Students_Col_EnrollNbr=>uniqid(),
        DBContract::$Students_Col_DateAdmission=>date('Y-m-d'));
    echo '<br>we will upate with <br>';
    print_r($s);
    $db_manager->updateStudent(3,$s);
    */
    $db_manager->deleteStudent(6);
    ?>
</pre>

